/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistaEscritorio;


public class AplicacionTesting extends javax.swing.JFrame {

    /**
     * Creates new form AplicacionTesting
     */
    public AplicacionTesting() {
        initComponents();
        setTitle("Testing");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemLogin = new javax.swing.JMenuItem();
        itemMonitoreo = new javax.swing.JMenuItem();
        itemRealizarLlamada = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Iniciar");

        itemLogin.setText("Login");
        itemLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLoginActionPerformed(evt);
            }
        });
        jMenu1.add(itemLogin);

        itemMonitoreo.setText("Monitoreo");
        itemMonitoreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMonitoreoActionPerformed(evt);
            }
        });
        jMenu1.add(itemMonitoreo);

        itemRealizarLlamada.setText("Realizar llamada");
        itemRealizarLlamada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRealizarLlamadaActionPerformed(evt);
            }
        });
        jMenu1.add(itemRealizarLlamada);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemRealizarLlamadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRealizarLlamadaActionPerformed
        new VistaSimularLlamada(false).setVisible(true);
    }//GEN-LAST:event_itemRealizarLlamadaActionPerformed

    private void itemLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLoginActionPerformed
        new VistaLogin(false).setVisible(true);
    }//GEN-LAST:event_itemLoginActionPerformed

    private void itemMonitoreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMonitoreoActionPerformed
        new VistaMonitoreo().setVisible(true);
    }//GEN-LAST:event_itemMonitoreoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemLogin;
    private javax.swing.JMenuItem itemMonitoreo;
    private javax.swing.JMenuItem itemRealizarLlamada;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
