/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistaEscritorio;

import controlador.IvistaAtenderLlamadas;
import controlador.controladorAtenderLlamada;
import javax.swing.JOptionPane;
import modelo.Llamada;
import modelo.Trabajador;

public class VistaAtenderLlamadas extends javax.swing.JFrame implements IvistaAtenderLlamadas {

    private controladorAtenderLlamada controlador;

    /**
     * Creates new form VentanaAtenderLlamadas
     */
    public VistaAtenderLlamadas(Trabajador unTrabajador) {
        initComponents();
        setTitle("Atender Llamadas");
        setLocationRelativeTo(null);
        controlador = new controladorAtenderLlamada(this, unTrabajador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDescripcion = new javax.swing.JTextArea();
        bFinalizar = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        lbCliente = new javax.swing.JLabel();
        lbSector = new javax.swing.JLabel();
        lbLlamadasAtendidas = new javax.swing.JLabel();
        lbTiempoPromedio = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        lbPuesto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Descripcion:");

        taDescripcion.setColumns(20);
        taDescripcion.setRows(5);
        jScrollPane1.setViewportView(taDescripcion);

        bFinalizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bFinalizar.setForeground(new java.awt.Color(255, 0, 0));
        bFinalizar.setText("Finalizar llamada");
        bFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFinalizarActionPerformed(evt);
            }
        });

        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        lbCliente.setText("Cliente:");

        lbSector.setText("Sector:");

        lbLlamadasAtendidas.setText("Llamadas atendidas:");

        lbTiempoPromedio.setText("Tiempo promedio:");

        lbNombre.setText("Nombre:");

        lbPuesto.setText("Puesto Nro. #");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(lbCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbNombre)
                        .addContainerGap(670, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbSector)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbLlamadasAtendidas)
                        .addGap(155, 155, 155)
                        .addComponent(lbTiempoPromedio)
                        .addGap(66, 66, 66))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbPuesto)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(180, 180, 180)
                                    .addComponent(bFinalizar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bSalir))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(lbNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbSector))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbLlamadasAtendidas)
                            .addComponent(lbTiempoPromedio))))
                .addGap(18, 18, 18)
                .addComponent(lbPuesto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(lbCliente)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(85, 85, 85)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bFinalizar)
                    .addComponent(bSalir))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        controlador.salir();
    }//GEN-LAST:event_formWindowClosing

    private void bFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFinalizarActionPerformed
        // TODO add your handling code here:
        controlador.finalizarLlamada();
    }//GEN-LAST:event_bFinalizarActionPerformed

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        // TODO add your handling code here:
        controlador.salir();
    }//GEN-LAST:event_bSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bFinalizar;
    private javax.swing.JButton bSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCliente;
    private javax.swing.JLabel lbLlamadasAtendidas;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbPuesto;
    private javax.swing.JLabel lbSector;
    private javax.swing.JLabel lbTiempoPromedio;
    private javax.swing.JTextArea taDescripcion;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrarDetalles(Trabajador unTrabajador) {
        lbNombre.setText(unTrabajador.getNombreCompleto());
        lbSector.setText("Sector: " + unTrabajador.getSector().toString());
    }

    @Override
    public void mostrarDetallesTrabajadorConPuesto(Trabajador unTrabajador) {
        lbLlamadasAtendidas.setText("Llamadas atendidas: " + unTrabajador.getPuesto().cantidadLlamadasAtendidasPorTrabajador());
        lbPuesto.setText("Puesto Nro. #" + unTrabajador.getPuesto().getNumero());
        lbTiempoPromedio.setText("Tiempo promedio: " + unTrabajador.getPuesto().getTiempoDeLlamada());
    }

    @Override
    public void mostrarLlamadaEnCurso(Llamada llamadaActual) {
        lbCliente.setText("Llamada en curso con " + llamadaActual.getCliente().getNombreCompleto() + " iniciada el " + llamadaActual.getFechaHoraAtendida());
    }

    @Override
    public void finalizarLlamada() {
        taDescripcion.setText("");
        lbCliente.setText("Llamada Finalizada...");
    }
    

    @Override
    public void agregarDescripcion(Llamada unaLlamada) {
        unaLlamada.setDescripcion(taDescripcion.toString());
    }
    
    @Override
    public void cerrarVentana(){
        dispose();
    }
    

    @Override
    public void mostrarDialogo() {
        int r = JOptionPane.showConfirmDialog(this, "¿Desea finalizar la llamada y cerrar?");
        if (r == JOptionPane.YES_OPTION) {
            controlador.salirYAvisar();
            controlador.desloguear();
            dispose();
        }
    }
    
    @Override
    public void mostrarDialogoDeConfirmacion(){
        int r = JOptionPane.showConfirmDialog(this, "¿Confirma que desea cerrrar?");
        if (r == JOptionPane.YES_OPTION) {
            dispose();
        }
    }

}
